### PR TITLE
WIP: A proposal for `c2d`

### PR DESCRIPTION
**Pull request by aytekinar**
How do you think this looks?

### CODE REVIEW

**Comment by CristianRojas** [comment]
@aytekinar: Thanks for the code!

Regarding the questions in the TODO: Some discretization methods can be efficiently implemented for several types, such as `RationalTF`, `StateSpace` or `ZeroPoleGain`, hence it might be worth to define `c2d` so that the methods can take a general `LtiSystem` (and other specialized types, in case efficient algorithms exist for them), and return not A,B,C,D matrices but a system of the same type as the input. This would allow to have a ZOH discretization function `c2d(sys, Discretization.ZOH)` that can take a `RationalTF` or `StateState` object and return an object of the same type.

What do you think?

Cc: @neveritt

**Comment by aytekinar** [comment]
OK, so we are gonna proceed as usual? Specialize functions on our _library provided_ data types and write a catch-all on `LtiSystem` for convenience?

**Comment by CristianRojas** [comment]
Do you think that's fine? I don't know if there is a more convenient way to achieve this, I mean, to make `c2d` return the appropriate specialized type, and at the same type to have the possibility of specific methods for these types.

**Comment by aytekinar** [comment]
That has been, since the beginning, our thought with @neveritt. I mean, to write for abstractions while providing the versions which could result in efficient implementations.

**Comment by CristianRojas** [comment]
Great! Ok, let's do it that way then :)

**Pull request merged**
